# Generated by Django 4.0.6 on 2022-08-19 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_suscribers_about_email_about_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'Informacion Personal', 'verbose_name_plural': 'Sobre Nosotros'},
        ),
    ]
