# Generated by Django 4.0.6 on 2022-08-19 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrada', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='short_name',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=15, unique=True, verbose_name='Nombre Corto'),
        ),
    ]
