# Generated by Django 4.0.6 on 2022-08-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30, verbose_name='Nombre completo')),
                ('last_name', models.CharField(max_length=30, verbose_name='Apellido')),
                ('image', models.ImageField(upload_to='About', verbose_name='Foto')),
                ('date_birth', models.DateField(blank=True, null=True, verbose_name='fecha Nacimiento')),
                ('age', models.PositiveSmallIntegerField()),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'Sobre Nosotros',
            },
        ),
    ]
