# Generated by Django 4.0.6 on 2022-08-24 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_users_user_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_profile',
            options={'verbose_name': 'Perfil de Usuario', 'verbose_name_plural': 'Perfiles de Usuarios'},
        ),
    ]
