# Generated by Django 4.0.6 on 2022-08-24 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favoritos', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorites',
            unique_together=set(),
        ),
    ]
