# Generated by Django 4.0.6 on 2022-08-25 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favoritos', '0003_alter_favorites_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorites',
            unique_together=set(),
        ),
    ]
